import "../globals.css";
import ClientLayout from "./ClientLayout";
import { StateProvider } from "@/context/StateContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  minimumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateProvider>
          <ClientLayout>{children}</ClientLayout>
        </StateProvider>
      </body>
    </html>
  );
}
