import "../globals.css";

import { StateProvider } from "@/context/StateContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateProvider>
        <body>{children}</body>
      </StateProvider>
    </html>
  );
}
