import "../globals.css";

import ClientLayout from "./ClientLayout";
import { StateProvider } from "@/context/StateContext";

export const metadata = {
  title: "Rafaela Kaćunić",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // put favicon.ico in public/
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
  openGraph: {
    title: "Rafaela Kaćunić",
    siteName: "Rafaela Kaćunić",
    images: [
      {
        url: "/meta-image.jpg", // put in /public
        width: 1200,
        height: 630,
        alt: "Rafaela Kaćunić",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export const viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  minimumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="no-scroll">
        <StateProvider>
          <ClientLayout>{children}</ClientLayout>
        </StateProvider>
      </body>
    </html>
  );
}
